# --- START OF FILE pharmacy_report_tool.py ---

# import logging  # Commented out - not needed for hardcoded report
import os
import sys
import json
# import aiohttp  # Commented out - no API calls needed
from typing import Dict, Any
from datetime import datetime
from pathlib import Path

# Add the grandparent directory to sys.path for imports
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

from mcp.server.fastmcp import FastMCP
from pydantic import Field

# Import your existing Pydantic models from the FastAPI backend
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "../../..")))

from tool_bridge_mcp_server.context import get_app_context

# Import Config for proper directory paths
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "../..", "DashApp")))
try:
    from config import Config
except ImportError:
    # Fallback if config import fails
    class Config:
        @staticmethod
        def get_reports_path():
            return os.path.join(os.path.dirname(__file__), "../../reports")

import sys
import os
# Add project root to Python path for imports
current_dir = os.path.dirname(os.path.abspath(__file__))
project_root = os.path.dirname(os.path.dirname(current_dir))
if project_root not in sys.path:
    sys.path.insert(0, project_root)

from app_logger import get_logger
logger = get_logger(__name__)

# Configuration
# FASTAPI_BASE_URL = "http://localhost:8000"  # Commented out - no API calls needed

# Hardcoded report path using project root pattern like config.py
PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent
HARDCODED_REPORT_PATH = PROJECT_ROOT / "reports" / "pharmacy_report" / "report.md"

def register_pharmacy_report_tools(mcp: FastMCP):
    """Register pharmacy report generation tool."""

    logger.info("Registering pharmacy report tool with MCP server")

    # Commented out - no API calls needed for hardcoded report
    # async def call_pharmacy_report_api(request_body: Dict[str, Any], jwt_token: str) -> Dict[str, Any]:
    #     """Call the pharmacy report API internally"""
    #     url = f"{FASTAPI_BASE_URL}/fastapi/smart_pharmacy_report"
    #     
    #     headers = {
    #         "Content-Type": "application/json",
    #         "Authorization": f"Bearer {jwt_token}"
    #     }
    #     
    #     request_payload = {
    #         "message": "Pharmacy site analysis via MCP tool",
    #         "request_info": {},
    #         "request_body": request_body
    #     }
    #     
    #     logger.info(f"Calling pharmacy report API: {url}")
    #     
    #     try:
    #         async with aiohttp.ClientSession() as session:
    #             async with session.post(url, json=request_payload, headers=headers) as response:
    #                 logger.info(f"Pharmacy API response status: {response.status}")
    #                 
    #                 if response.status == 200:
    #                     response_data = await response.json()
    #                     logger.info("Pharmacy API call successful")
    #                     return response_data
    #                 else:
    #                     error_text = await response.text()
    #                     logger.error(f"Pharmacy API error: {response.status} - {error_text}")
    #                     return {"error": f"API returned {response.status}", "details": error_text}
    #                     
    #     except Exception as e:
    #         logger.error(f"Error calling pharmacy API: {e}")
    #         return {"error": "Request failed", "details": str(e)}

    def generate_simple_markdown_report(city_name: str) -> str:
        """Generate a simple markdown report with click here message"""
        try:
            current_date = datetime.now().strftime("%B %d, %Y")
            
            # Generate simple report with clickable link to full report
            report = f"""# Pharmacy Site Analysis Report - {city_name}

Analysis completed for {city_name} on {current_date}.

[Click here to see full report](/static/reports/pharmacy_report/riyadh_pharmacies/index.html)

---
Generated by Geospatial Intelligence Platform
"""
            return report
            
        except Exception as e:
            logger.error(f"Error generating markdown report: {str(e)}")
            return f"# Pharmacy Report Error\n\nFailed to generate report: {str(e)}"

    async def save_report_to_file(report_content: str, city_name: str, timestamp: str) -> tuple[str, str]:
        """Save the markdown report to the reports directory"""
        try:
            reports_dir = Config.get_reports_path()
            os.makedirs(reports_dir, exist_ok=True)
            
            # Generate filename
            safe_city_name = city_name.replace(' ', '_').replace('/', '_').replace('\\', '_')
            safe_city_name = ''.join(c for c in safe_city_name if c.isalnum() or c in '_-')
            
            filename = f"{safe_city_name}_pharmacy_report_{timestamp}.md"
            file_path = os.path.join(reports_dir, filename)
            
            # Save the report
            with open(file_path, 'w', encoding='utf-8') as f:
                f.write(report_content)
            
            logger.info(f"Report saved successfully: {filename}")
            return filename, f"Report saved: {filename}"
                
        except Exception as e:
            logger.error(f"Error saving report: {str(e)}")
            return "", f"Error saving report: {str(e)}"

    @mcp.tool(
        name="generate_pharmacy_report",
        description="""Generate comprehensive pharmacy site selection reports.
        
        Serves the hardcoded pharmacy analysis report for Riyadh.
        
        Returns the existing pharmacy site analysis report with detailed insights.
        """,
    )
    async def generate_pharmacy_report(
        city_name: str = Field(
            default="Riyadh",
            description="Target city for pharmacy site analysis"
        ),
        country_name: str = Field(
            default="Saudi Arabia", 
            description="Target country"
        ),
    ) -> str:
        """Serve the hardcoded pharmacy site selection analysis."""

        try:
            # Simplified authentication check - commented out for now
            # app_ctx = get_app_context(mcp)
            # session_manager = app_ctx.session_manager
            # user_id, id_token = await session_manager.get_valid_id_token()
            # if not id_token or not user_id:
            #     return "Error: You are not logged in. Please use the `user_login` tool first."

            logger.info(f"Generating pharmacy report for {city_name}, {country_name}")

            # Generate timestamp for filename
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            
            # Generate the report content
            report_content = generate_simple_markdown_report(city_name)
            
            # Save the report to file
            report_filename, save_message = await save_report_to_file(report_content, city_name, timestamp)
            
            if not report_filename:
                error_result = {
                    "report_file": "",
                    "data_files": {},
                    "response": f"❌ Error: {save_message}",
                    "metadata": {
                        "error": True,
                        "analysis_type": "pharmacy_site_selection",
                        "city": city_name
                    }
                }
                return json.dumps(error_result, ensure_ascii=False, indent=2)
            
            # Build response
            analysis_summary = f"✅ Pharmacy site analysis report generated for {city_name}, {country_name}.\n"
            analysis_summary += f"📄 Report: {report_filename}\n"
            analysis_summary += f"🔗 {save_message}"
            
            # Get full path to the saved report
            reports_dir = Config.get_reports_path()
            full_report_path = os.path.join(reports_dir, report_filename)
            
            # Return structured JSON format compatible with DashApp
            result = {
                "report_file": str(full_report_path),  # Full path for DashApp to read
                "data_files": {},
                "response": analysis_summary,
                "metadata": {
                    "analysis_type": "pharmacy_site_selection",
                    "city": city_name,
                    "country": country_name,
                    "report_generated": True,
                    "hardcoded_report": False
                }
            }
            return json.dumps(result, ensure_ascii=False, indent=2)

        except Exception as e:
            logger.exception(f"Error serving pharmacy report: {str(e)}")
            error_result = {
                "report_file": "",
                "data_files": {},
                "response": f"❌ Error: Failed to serve pharmacy report: {str(e)}",
                "metadata": {
                    "error": True,
                    "analysis_type": "pharmacy_site_selection",
                    "city": city_name
                }
            }
            return json.dumps(error_result, ensure_ascii=False, indent=2)